# Generated by Django 4.2.3 on 2023-07-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_tenant_email_alter_tenant_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
