# Generated by Django 4.2.3 on 2023-07-31 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_alter_tenant_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='idPassport',
            new_name='id_passport',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='phone',
            new_name='phone_no',
        ),
    ]
