# Generated by Django 4.2.3 on 2023-08-04 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0003_alter_landlord_company_alter_landlord_email'),
        ('tenant', '0004_rename_firstname_tenant_first_name_and_more'),
        ('agreement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='landlord',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='landlord.landlord'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='tenant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='tenant.tenant'),
        ),
    ]
