# Generated by Django 4.2.3 on 2023-07-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0002_unit_property_unit_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('V', 'VACANT'), ('O', 'OCCUPIED'), ('U', 'UNDER MAINTENANCE')], default='V', max_length=1),
        ),
    ]
