# Generated by Django 4.2.3 on 2023-08-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0002_rename_phone_landlord_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
