# Generated by Django 4.2.3 on 2023-07-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('photos', models.JSONField()),
                ('status', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
