# Generated by Django 4.2.3 on 2023-07-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=1000)),
                ('no_of_units', models.IntegerField()),
                ('rental_price', models.IntegerField()),
            ],
        ),
    ]
