# Generated by Django 4.2.3 on 2023-07-31 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landlord.landlord'),
        ),
    ]
